# Generated by Django 6.0.2 on 2026-03-12 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='village',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='district',
            name='state',
        ),
        migrations.AlterField(
            model_name='village',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='locations.district'),
        ),
    ]
